### ISSUE TITLE
notes: Installing code formatter in VS Code

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#1480]
Work in progresso:

* npm install -g prettier prettier-plugin-go-template@0.0.11-beta.11
* See https://github.com/NiklasPor/prettier-plugin-go-template/pull/49 for the status of the beta above
* `ext install esbenp.prettier-vscode` (https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)
* Set `prettier.resolveGlobalModules` to  `true`

**Comment by coliff** [comment]
looks interesting! Could also consider adding a `.vscode/extensions.json` to the repo with something like:

```json
{
  "recommendations": [
    "EditorConfig.EditorConfig",
    "esbenp.prettier-vscode"
  ]
}
```
Then when someone opens the repo in VS Code it'll suggest installing those two extensions.

**Comment by bep** [comment]
Oh, well, I spent an hour today and couldn't get this to work, but this is important enough (and seemingly hard enough to get right) to get into the docs. 

I saw @andreseduardop commenting that he got it to work with VS Code ... any tips?

**Comment by andreseduardop** [comment]
@bep, I did a couple of things differently.

- I use beta 13 instead of 11.
- I install prettier and the plugin in the local context (not global), with:
`npm install --save-dev prettier prettier-plugin-go-template@0.0.11-beta.13`

For clarity, these are all the steps I did to get Prettier and the Go plugin to work properly in VS Code:

0. **Start with a clean install.** (This may not be necessary, but I did.)
In VS Code uninstall the "Prettier - Code formatter" extension.
Also, run in console:
`npm uninstall -g prettier prettier-plugin-go-template`
and
`npm uninstall prettier prettier-plugin-go-template`

1. **Install locally in the repo: Prettier and Prettier-plugin-go-template (beta 13)**:
`npm install --save-dev prettier prettier-plugin-go-template@0.0.11-beta.13`
_(Apparently a local installation is required in the repo, for the VS Code extension to recognize the plugin-go-template.)_

2. **In VS Code install the extension** "[Prettier - Code formatter](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)".

3. Inside the root directory of the repo **add**:

`.prettierrc `file, with this content:
```json
{
  "overrides": [
    {
      "files": ["*.html"],
      "options": {
        "parser": "go-template"
      }
    }
  ]
}
```

`/.vscode/settings.json` file, with this content:
```json
{
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
}
```
_Without this last file, Prettier is not configured as the formatter to use._

4. In VS Code, inside a hugo template, `Ctrl + Shift + P` then 'Format Document'.

The result obtained is ...
test-file-before.html => test-file-after.html 

![Captura](https://user-images.githubusercontent.com/59033733/123501496-fac28080-d60a-11eb-887a-9ed399264a19.PNG)

`If/else` and `with/else`, working correctly.
There is [a little problem](https://github.com/NiklasPor/prettier-plugin-go-template/issues/52) with short multi-line `dict`. With the help of Niklas, I hope it will be fixed soon.

**Comment by NiklasPor** [comment]
The _little problem_ is fixed 😁

**Comment by NiklasPor** [comment]
The workflow described by @andreseduardop seems correct to me. Prettier also mentions that you can install both prettier & the plugins globally to use them with the VSCode extension, but I've only tried it out with setting up everything locally.

![image](https://user-images.githubusercontent.com/13211347/123508331-06479300-d66f-11eb-8a13-300a3d1d099e.png)

**Comment by NiklasPor** [comment]
Also this issue is relevant if we're aiming for 0 config at some point: https://github.com/gohugoio/hugo/issues/3230

**Comment by andreseduardop** [comment]
New versión, **prettier-plugin-go-template@0.0.11** It is working fine for me, in VS Code.  Thanks, @NiklasPor. 👍 🚀 
https://github.com/NiklasPor/prettier-plugin-go-template/pull/49#issuecomment-868978848

It's still broken in Sublime Text with JsPrettier. 😔

**Comment by NiklasPor** [comment]
I'll try to investigate in the sublime issue then 👀
